<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TUBES_KPL</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<Content Include="categories.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="role_permission.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="sla_rules.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="notification_templates.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="TUBES_KPL.API\**" />
		<Content Remove="TUBES_KPL.API\**" />
		<None Remove="TUBES_KPL.API\**" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="TUBES_KPL.Tests\**" />
		<Content Remove="TUBES_KPL.Tests\**" />
		<None Remove="TUBES_KPL.Tests\**" />
	</ItemGroup>

</Project>
